package pingo

const (
	GPIOHANDLES_MAX = 64

	// Ioctl commands
	GPIO_GET_CHIPINFO_IOCTL          = 0x8044b401
	GPIO_GET_LINEINFO_IOCTL          = 0xc048b402
	GPIO_GET_LINEHANDLE_IOCTL        = 0xc16cb403
	GPIOHANDLE_SET_LINE_VALUES_IOCTL = 0xC040B409
	GPIOHANDLE_GET_LINE_VALUES_IOCTL = 0xC040B408
	GPIO_GET_LINEEVENT_IOCTL         = 0xC030B004
	GPIO_V2_GET_LINE_IOCTL           = 0xC250B403

	// Flags
	GPIOHANDLE_REQUEST_INPUT       = 1 << 0
	GPIOHANDLE_REQUEST_OUTPUT      = 1 << 1
	GPIOHANDLE_REQUEST_ACTIVE_LOW  = 1 << 2
	GPIOHANDLE_REQUEST_OPEN_DRAIN  = 1 << 3
	GPIOHANDLE_REQUEST_OPEN_SOURCE = 1 << 4

	GPIOEVENT_REQUEST_RISING_EDGE  = 1 << 0
	GPIOEVENT_REQUEST_FALLING_EDGE = 1 << 1
	GPIOEVENT_REQUEST_BOTH_EDGES   = (1 << 0) | (1 << 1)

	GPIOEVENT_EVENT_RISING_EDGE  = 0x01
	GPIOEVENT_EVENT_FALLING_EDGE = 0x02

	// v2 API event types
	GPIO_V2_LINE_EVENT_RISING_EDGE  = 1
	GPIO_V2_LINE_EVENT_FALLING_EDGE = 2

	// v2 API flags
	GPIO_V2_LINE_FLAG_INPUT        = 1 << 2
	GPIO_V2_LINE_FLAG_EDGE_RISING  = 1 << 3
	GPIO_V2_LINE_FLAG_EDGE_FALLING = 1 << 4

	GPIO_V2_LINE_ATTR_ID_FLAGS = 1
	GPIO_V2_LINE_ATTR_ID_EDGE  = 2

	GPIO_V2_LINE_EDGE_NONE    = 0
	GPIO_V2_LINE_EDGE_RISING  = 1
	GPIO_V2_LINE_EDGE_FALLING = 2
	GPIO_V2_LINE_EDGE_BOTH    = 3

	GPIO_V2_LINE_NUM_ATTRS_MAX         = 10
	GPIO_V2_LINES_MAX                  = 64
	GPIO_MAX_NAME_SIZE                 = 32
	GPIO_V2_LINE_ATTR_ID_OUTPUT_VALUES = 2
)
