package pingo

const (
	GPIOHANDLES_MAX = 64

	// Ioctl commands
	GPIO_GET_CHIPINFO_IOCTL          = 0x8044b401
	GPIO_GET_LINEINFO_IOCTL          = 0xc048b402
	GPIO_GET_LINEHANDLE_IOCTL        = 0xc16cb403
	GPIOHANDLE_SET_LINE_VALUES_IOCTL = 0xC040B409
	GPIOHANDLE_GET_LINE_VALUES_IOCTL = 0xC040B408
	GPIO_GET_LINEEVENT_IOCTL         = 0xC030B004
	GPIO_V2_GET_LINE_IOCTL           = 0xc020df03

	// Flags
	GPIOHANDLE_REQUEST_INPUT       = 1 << 0
	GPIOHANDLE_REQUEST_OUTPUT      = 1 << 1
	GPIOHANDLE_REQUEST_ACTIVE_LOW  = 1 << 2
	GPIOHANDLE_REQUEST_OPEN_DRAIN  = 1 << 3
	GPIOHANDLE_REQUEST_OPEN_SOURCE = 1 << 4

	GPIOEVENT_REQUEST_RISING_EDGE  = 0x1
	GPIOEVENT_REQUEST_FALLING_EDGE = 0x2
	GPIOEVENT_REQUEST_BOTH_EDGES   = 0x3

	GPIOEVENT_EVENT_RISING_EDGE  = 0x01
	GPIOEVENT_EVENT_FALLING_EDGE = 0x02

	// v2 API event types
	GPIO_V2_LINE_EVENT_RISING_EDGE  = 1
	GPIO_V2_LINE_EVENT_FALLING_EDGE = 2
)
